ci pipeline modified .next folder

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -64,6 +64,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: build-output
+          include-hidden-files: true
           path: |
             .next
             public
@@ -93,6 +94,10 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: build-output
+          path: .
+
+      - name: Debug - List files
+        run: ls -la && ls -la .next || echo ".next not found"
 
       - name: Install dependencies (Production only)
         run: npm ci --omit=dev
